### ISSUE TITLE
What's the license for this software?

### ISSUE THREAD

**Issue by davidtbo** [doc-han/xtensio#15]
If you want people to build with this you should put a license on the project. Otherwise there's no telling if people are allowed to use this software to build into their projects. If you want to make it commercially-friendly to integrate into products, you should pick something like Apache 2 or MIT licensing.

**Comment by doc-han** [comment]
Thanks for the suggestion! We’re going with the MIT license to keep it simple and commercially friendly.

**Comment by doc-han** [comment]
Resolved #16
